MODEL:
  META_ARCHITECTURE: "Qwen3D"
  WEIGHTS: ""
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "SimpleMaskDecoder" # change this so default is the simple mask decoder
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    GENERATION_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    PRE_NORM: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
DATASETS:
  TRAIN: ("scannet_context_instance_train_20cls_single_100k",)
  TEST: ("scannet_context_instance_val_200_single_100k",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  STEPS: (1000000,)
  MAX_ITER: 8000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
    DTYPE: "float16"
INPUT:
  MIN_SIZE_TRAIN: (320,)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST_SAMPLING: "choice"
  MIN_SIZE_TEST: 320
  MAX_SIZE_TRAIN: 320
  MAX_SIZE_TEST: 320
  IMAGE_SIZE: 320
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  CROP:
    ENABLED: False
    TYPE: "absolute"
    SIZE: (640, 640)
  SIZE_DIVISIBILITY: 32  # for now disabeld.
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 800
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
  TEST_NUM_WORKERS: 4
VERSION: 2
